---
- hosts: all
  become: true
  vars:
    pkg1: httpd
    pkg2: apache2
  tasks:
    - name: Install Packages
      package:
        name: "{{item}}"
        state: present
      loop:
        - wget
        - git
    - name: Install httpd
      yum:
        name: "{{pkg1}}"
        state: present
      when: ansible_facts['os_family'] == "RedHat"

    - name: Install apache
      apt:
        name: "{{pkg2}}"
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: copy index file
      ansible.builtin.copy:
        src: ./index.html
        dest: /var/www/html
        owner: root
        group: root
        mode: '0644'
      notify: copied

  handlers:
    - name: copied
      service:
        name: httpd
        state: restarted
      when: ansible_distribution == "RedHat"

    - name: copied
      service:
        name: apache2
        state: started
      when: ansible_distribution == "Ubuntu"
