- hosts: all
  gather_facts: yes
  tasks:
    - name: gather facts
      debug:
        msg:
           name: "{{ansible_hostname}}"
           os: "{{ansible_distribution}}"
           version: "{{ansible_distribution_major_version}}"
           ip_addtress: "{{ansible_default_ipv4.address}}"
           dns: "{{ansible_dns.nameservers}}"
