---
- hosts: all
  become: true
  vars:
    pkg1: httpd
    pkg2: apache2
  tasks:
  - name: stopping httpd service
    service:
        name: httpd
        state: stopped
    when: ansible_distribution == "RedHat"

  - name: stopping apache service
    service:
        name: apache2
        state: stopped
    when: ansible_distribution == "Ubuntu"

  - name: UnInstall httpd
    yum:
        name: "{{pkg1}}"
        state: absent
    when: ansible_facts['os_family'] == "RedHat"

  - name: UnInstall apache
    apt:
        name: "{{pkg2}}"
        state: absent
    when: ansible_distribution == "Ubuntu"

    
    
