---
# tasks file for ec2
- name: start an instance with a public IP address
  amazon.aws.ec2_instance:
      name: "ansible-instance"
      key_name: "web_service"
      # vpc_subnet_id: subnet-013744e41e8088axx
      instance_type: t2.micro
      security_group: default
      region: us-east-1
      aws_access_key: "{{ec2_access_key}}"  # From vault as defined
      aws_secret_key: "{{ec2_secret_key}}"  # From vault as defined      
      network:
        assign_public_ip: true
      image_id: ami-04a81a99f5ec58529
      tags:
        Environment: Testing
