---
- hosts: web
  become: yes
  tasks:

    - name: show uptime
      command: uptime
      register: upt

    - debug:
        msg: "{{upt.stdout_lines}}"

    - name: print host
      debug:
        msg: host "{{ansible_hostname}}"

    - debug:
        var: upt
